documentation:
  - changed-files:
      - any-glob-to-any-file: ['.github/*', '**/*.md']

enhancement:
  - changed-files:
      - any-glob-to-any-file: ['FinBoxRiskManager/*', 'RiskManager/*', 'RiskManagerTests/*']
