name: "Enforce Branch Merge Rules"

on:
  pull_request:
    branches:
      - main
      - release

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce develop -> release
        if: github.event.pull_request.base.ref == 'release' && github.event.pull_request.head.ref != 'develop'
        run: |
          echo "Only the develop branch can be merged into the release branch."
          exit 1

      - name: Enforce release/hotfix -> main
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'release' && github.event.pull_request.head.ref != 'hotfix'
        run: |
          echo "Only the release or hotfix branch can be merged into the main branch."
          exit 1
